server {
  listen 80;
  listen [::]:80;
  server_name www.terraxopc.com;

  return 301 https://terraxopc.com$request_uri;
}

server {
  listen 80;
  listen [::]:80;
  server_name terraxopc.com;

  root /var/www/terraxopc.com;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
